name = "clef"
version = "0.0.1"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
glitzer = ">= 2.0.0 and < 3.0.0"
shellout = ">= 1.7.0 and < 2.0.0"
glint = ">= 1.2.1 and < 2.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleescript = ">= 1.5.2 and < 2.0.0"
